### PR TITLE
Mongoose DB, Plugins, Users, Refactoring (and possibly more)

### PR DESCRIPTION
**Pull request by 4Benj**
# Description
These are various additions and changes to the API. Check the feature/todo list

# Feature/Todo List
- [x] Refactoring
- [x] Database
- [x] Data Validation/Creation
- [ ] Plugin Repository (in progress)
 - [ ] Maybe: Plugin Resources (Images in the description) 
- [x] Users 
 - [ ] Maybe: User profile pictures and bio
- [x] Settings/Config relocated to DB
- [ ] Admin Route
- [ ] Move configuration to an admin route
- [x] Maintenance mode
- [x] Better logging
- [x] Mailing
- [ ] Audit Log
Possibly more later

### CODE REVIEW

**Review by KingRainbow44 — CHANGES_REQUESTED** [review]
Can we get more typing on everything? (ie. `const foo: <type> = bar;`)
also pls stop using `var` in 2022

**Review by danieldll099 — APPROVED** [review]
tha ks

**Comment by danieldll099** [comment]
- [ ] thanks[]()

**Comment by 4Benj** [comment]
?

**Review by danieldll099 — APPROVED** [review]
Good[]()

**Pull request closed without merging**
